# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_album_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_introduction',
            field=models.TextField(),
        ),
    ]
