# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20161213_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_introduction',
            field=models.TextField(default='&nbsp; &nbsp; &nbsp; &nbsp;'),
        ),
    ]
