# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20161214_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_introduction',
            field=models.TextField(default='    '),
        ),
    ]
